// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface CreateRoomIntentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateRoomIntent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string room_name = 1;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>optional string room_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();
}
