// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws.proto

package proto;

public interface InvitationAcceptedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InvitationAcceptedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 invitation_id = 1;</code>
   */
  int getInvitationId();

  /**
   * <code>optional int32 friend_id = 2;</code>
   */
  int getFriendId();

  /**
   * <code>optional string friend_name = 3;</code>
   */
  java.lang.String getFriendName();
  /**
   * <code>optional string friend_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFriendNameBytes();
}
