// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws.proto

package proto;

public interface InvitationEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InvitationEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 invitation_id = 1;</code>
   */
  int getInvitationId();

  /**
   * <code>optional string sender_name = 2;</code>
   */
  java.lang.String getSenderName();
  /**
   * <code>optional string sender_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getSenderNameBytes();

  /**
   * <code>optional string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
