// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws.proto

package proto;

/**
 * Protobuf type {@code InvitationAcceptedEvent}
 */
public  final class InvitationAcceptedEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InvitationAcceptedEvent)
    InvitationAcceptedEventOrBuilder {
  // Use InvitationAcceptedEvent.newBuilder() to construct.
  private InvitationAcceptedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InvitationAcceptedEvent() {
    invitationId_ = 0;
    friendId_ = 0;
    friendName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private InvitationAcceptedEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            invitationId_ = input.readInt32();
            break;
          }
          case 16: {

            friendId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            friendName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Ws.internal_static_InvitationAcceptedEvent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Ws.internal_static_InvitationAcceptedEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.InvitationAcceptedEvent.class, proto.InvitationAcceptedEvent.Builder.class);
  }

  public static final int INVITATION_ID_FIELD_NUMBER = 1;
  private int invitationId_;
  /**
   * <code>optional int32 invitation_id = 1;</code>
   */
  public int getInvitationId() {
    return invitationId_;
  }

  public static final int FRIEND_ID_FIELD_NUMBER = 2;
  private int friendId_;
  /**
   * <code>optional int32 friend_id = 2;</code>
   */
  public int getFriendId() {
    return friendId_;
  }

  public static final int FRIEND_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object friendName_;
  /**
   * <code>optional string friend_name = 3;</code>
   */
  public java.lang.String getFriendName() {
    java.lang.Object ref = friendName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      friendName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string friend_name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFriendNameBytes() {
    java.lang.Object ref = friendName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      friendName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (invitationId_ != 0) {
      output.writeInt32(1, invitationId_);
    }
    if (friendId_ != 0) {
      output.writeInt32(2, friendId_);
    }
    if (!getFriendNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, friendName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (invitationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, invitationId_);
    }
    if (friendId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, friendId_);
    }
    if (!getFriendNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, friendName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.InvitationAcceptedEvent)) {
      return super.equals(obj);
    }
    proto.InvitationAcceptedEvent other = (proto.InvitationAcceptedEvent) obj;

    boolean result = true;
    result = result && (getInvitationId()
        == other.getInvitationId());
    result = result && (getFriendId()
        == other.getFriendId());
    result = result && getFriendName()
        .equals(other.getFriendName());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + INVITATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInvitationId();
    hash = (37 * hash) + FRIEND_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFriendId();
    hash = (37 * hash) + FRIEND_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFriendName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.InvitationAcceptedEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.InvitationAcceptedEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.InvitationAcceptedEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.InvitationAcceptedEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.InvitationAcceptedEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.InvitationAcceptedEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.InvitationAcceptedEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.InvitationAcceptedEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.InvitationAcceptedEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.InvitationAcceptedEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.InvitationAcceptedEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InvitationAcceptedEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InvitationAcceptedEvent)
      proto.InvitationAcceptedEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Ws.internal_static_InvitationAcceptedEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Ws.internal_static_InvitationAcceptedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.InvitationAcceptedEvent.class, proto.InvitationAcceptedEvent.Builder.class);
    }

    // Construct using proto.InvitationAcceptedEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      invitationId_ = 0;

      friendId_ = 0;

      friendName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Ws.internal_static_InvitationAcceptedEvent_descriptor;
    }

    public proto.InvitationAcceptedEvent getDefaultInstanceForType() {
      return proto.InvitationAcceptedEvent.getDefaultInstance();
    }

    public proto.InvitationAcceptedEvent build() {
      proto.InvitationAcceptedEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public proto.InvitationAcceptedEvent buildPartial() {
      proto.InvitationAcceptedEvent result = new proto.InvitationAcceptedEvent(this);
      result.invitationId_ = invitationId_;
      result.friendId_ = friendId_;
      result.friendName_ = friendName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.InvitationAcceptedEvent) {
        return mergeFrom((proto.InvitationAcceptedEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.InvitationAcceptedEvent other) {
      if (other == proto.InvitationAcceptedEvent.getDefaultInstance()) return this;
      if (other.getInvitationId() != 0) {
        setInvitationId(other.getInvitationId());
      }
      if (other.getFriendId() != 0) {
        setFriendId(other.getFriendId());
      }
      if (!other.getFriendName().isEmpty()) {
        friendName_ = other.friendName_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.InvitationAcceptedEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.InvitationAcceptedEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int invitationId_ ;
    /**
     * <code>optional int32 invitation_id = 1;</code>
     */
    public int getInvitationId() {
      return invitationId_;
    }
    /**
     * <code>optional int32 invitation_id = 1;</code>
     */
    public Builder setInvitationId(int value) {
      
      invitationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 invitation_id = 1;</code>
     */
    public Builder clearInvitationId() {
      
      invitationId_ = 0;
      onChanged();
      return this;
    }

    private int friendId_ ;
    /**
     * <code>optional int32 friend_id = 2;</code>
     */
    public int getFriendId() {
      return friendId_;
    }
    /**
     * <code>optional int32 friend_id = 2;</code>
     */
    public Builder setFriendId(int value) {
      
      friendId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 friend_id = 2;</code>
     */
    public Builder clearFriendId() {
      
      friendId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object friendName_ = "";
    /**
     * <code>optional string friend_name = 3;</code>
     */
    public java.lang.String getFriendName() {
      java.lang.Object ref = friendName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string friend_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFriendNameBytes() {
      java.lang.Object ref = friendName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string friend_name = 3;</code>
     */
    public Builder setFriendName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      friendName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string friend_name = 3;</code>
     */
    public Builder clearFriendName() {
      
      friendName_ = getDefaultInstance().getFriendName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string friend_name = 3;</code>
     */
    public Builder setFriendNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      friendName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:InvitationAcceptedEvent)
  }

  // @@protoc_insertion_point(class_scope:InvitationAcceptedEvent)
  private static final proto.InvitationAcceptedEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.InvitationAcceptedEvent();
  }

  public static proto.InvitationAcceptedEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InvitationAcceptedEvent>
      PARSER = new com.google.protobuf.AbstractParser<InvitationAcceptedEvent>() {
    public InvitationAcceptedEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new InvitationAcceptedEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InvitationAcceptedEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InvitationAcceptedEvent> getParserForType() {
    return PARSER;
  }

  public proto.InvitationAcceptedEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

