// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface JoinRoomIntentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JoinRoomIntent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>optional string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();
}
