// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface MessageSendEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageSendEvent)
    com.google.protobuf.MessageOrBuilder {
}
