// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface MessageNotSendEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageNotSendEvent)
    com.google.protobuf.MessageOrBuilder {
}
