// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface MessageReceivedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageReceived)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string sender_name = 1;</code>
   */
  java.lang.String getSenderName();
  /**
   * <code>optional string sender_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderNameBytes();

  /**
   * <code>optional string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>optional string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
