// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface RoomNotLeftEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomNotLeftEvent)
    com.google.protobuf.MessageOrBuilder {
}
