// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface RoomNotJoinedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomNotJoinedEvent)
    com.google.protobuf.MessageOrBuilder {
}
