// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface RoomNotLeavedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomNotLeavedEvent)
    com.google.protobuf.MessageOrBuilder {
}
