// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface RoomsInfoEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomsInfoEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Room list = 1;</code>
   */
  java.util.List<proto.Room> 
      getListList();
  /**
   * <code>repeated .Room list = 1;</code>
   */
  proto.Room getList(int index);
  /**
   * <code>repeated .Room list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .Room list = 1;</code>
   */
  java.util.List<? extends proto.RoomOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .Room list = 1;</code>
   */
  proto.RoomOrBuilder getListOrBuilder(
      int index);
}
