// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface RoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Room)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .User members = 3;</code>
   */
  java.util.List<proto.User> 
      getMembersList();
  /**
   * <code>repeated .User members = 3;</code>
   */
  proto.User getMembers(int index);
  /**
   * <code>repeated .User members = 3;</code>
   */
  int getMembersCount();
  /**
   * <code>repeated .User members = 3;</code>
   */
  java.util.List<? extends proto.UserOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <code>repeated .User members = 3;</code>
   */
  proto.UserOrBuilder getMembersOrBuilder(
      int index);
}
