// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface RoomNotCreatedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomNotCreatedEvent)
    com.google.protobuf.MessageOrBuilder {
}
