// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface SendMessageIntentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessageIntent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string data = 1;</code>
   */
  java.lang.String getData();
  /**
   * <code>optional string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
