// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface SignalingIntentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignalingIntent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .CreateRoomIntent create_room = 1;</code>
   */
  proto.CreateRoomIntent getCreateRoom();
  /**
   * <code>optional .CreateRoomIntent create_room = 1;</code>
   */
  proto.CreateRoomIntentOrBuilder getCreateRoomOrBuilder();

  /**
   * <code>optional .JoinRoomIntent join_room = 2;</code>
   */
  proto.JoinRoomIntent getJoinRoom();
  /**
   * <code>optional .JoinRoomIntent join_room = 2;</code>
   */
  proto.JoinRoomIntentOrBuilder getJoinRoomOrBuilder();

  /**
   * <code>optional .LeaveRoomIntent leave_room = 3;</code>
   */
  proto.LeaveRoomIntent getLeaveRoom();
  /**
   * <code>optional .LeaveRoomIntent leave_room = 3;</code>
   */
  proto.LeaveRoomIntentOrBuilder getLeaveRoomOrBuilder();

  public proto.SignalingIntent.IntentCase getIntentCase();
}
