// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

/**
 * Protobuf type {@code SignalingEvent}
 */
public  final class SignalingEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SignalingEvent)
    SignalingEventOrBuilder {
  // Use SignalingEvent.newBuilder() to construct.
  private SignalingEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignalingEvent() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SignalingEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            proto.RoomsInfoEvent.Builder subBuilder = null;
            if (eventCase_ == 1) {
              subBuilder = ((proto.RoomsInfoEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomsInfoEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomsInfoEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 1;
            break;
          }
          case 18: {
            proto.RoomCreatedEvent.Builder subBuilder = null;
            if (eventCase_ == 2) {
              subBuilder = ((proto.RoomCreatedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomCreatedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomCreatedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 2;
            break;
          }
          case 26: {
            proto.RoomNotCreatedEvent.Builder subBuilder = null;
            if (eventCase_ == 3) {
              subBuilder = ((proto.RoomNotCreatedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomNotCreatedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomNotCreatedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 3;
            break;
          }
          case 34: {
            proto.RoomJoinedEvent.Builder subBuilder = null;
            if (eventCase_ == 4) {
              subBuilder = ((proto.RoomJoinedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomJoinedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomJoinedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 4;
            break;
          }
          case 42: {
            proto.RoomNotJoinedEvent.Builder subBuilder = null;
            if (eventCase_ == 5) {
              subBuilder = ((proto.RoomNotJoinedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomNotJoinedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomNotJoinedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 5;
            break;
          }
          case 50: {
            proto.RoomLeavedEvent.Builder subBuilder = null;
            if (eventCase_ == 6) {
              subBuilder = ((proto.RoomLeavedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomLeavedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomLeavedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 6;
            break;
          }
          case 58: {
            proto.RoomNotLeavedEvent.Builder subBuilder = null;
            if (eventCase_ == 7) {
              subBuilder = ((proto.RoomNotLeavedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomNotLeavedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomNotLeavedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 7;
            break;
          }
          case 66: {
            proto.RoomRemovedEvent.Builder subBuilder = null;
            if (eventCase_ == 8) {
              subBuilder = ((proto.RoomRemovedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.RoomRemovedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.RoomRemovedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 8;
            break;
          }
          case 74: {
            proto.MessageReceived.Builder subBuilder = null;
            if (eventCase_ == 9) {
              subBuilder = ((proto.MessageReceived) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.MessageReceived.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.MessageReceived) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 9;
            break;
          }
          case 82: {
            proto.MessageSendEvent.Builder subBuilder = null;
            if (eventCase_ == 10) {
              subBuilder = ((proto.MessageSendEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.MessageSendEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.MessageSendEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 10;
            break;
          }
          case 90: {
            proto.MessageNotSendEvent.Builder subBuilder = null;
            if (eventCase_ == 11) {
              subBuilder = ((proto.MessageNotSendEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.MessageNotSendEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.MessageNotSendEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 11;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Signaling.internal_static_SignalingEvent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Signaling.internal_static_SignalingEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.SignalingEvent.class, proto.SignalingEvent.Builder.class);
  }

  private int eventCase_ = 0;
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite {
    ROOMS_INFO(1),
    ROOM_CREATED(2),
    ROOM_NOT_CREATED(3),
    ROOM_JOINED(4),
    ROOM_NOT_JOINED(5),
    ROOM_LEAVED(6),
    ROOM_NOT_LEAVED(7),
    ROOM_REMOVED(8),
    MESSAGE_RECEIVED(9),
    MESSAGE_SEND(10),
    MESSAGE_NOT_SEND(11),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return ROOMS_INFO;
        case 2: return ROOM_CREATED;
        case 3: return ROOM_NOT_CREATED;
        case 4: return ROOM_JOINED;
        case 5: return ROOM_NOT_JOINED;
        case 6: return ROOM_LEAVED;
        case 7: return ROOM_NOT_LEAVED;
        case 8: return ROOM_REMOVED;
        case 9: return MESSAGE_RECEIVED;
        case 10: return MESSAGE_SEND;
        case 11: return MESSAGE_NOT_SEND;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int ROOMS_INFO_FIELD_NUMBER = 1;
  /**
   * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
   */
  public proto.RoomsInfoEvent getRoomsInfo() {
    if (eventCase_ == 1) {
       return (proto.RoomsInfoEvent) event_;
    }
    return proto.RoomsInfoEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
   */
  public proto.RoomsInfoEventOrBuilder getRoomsInfoOrBuilder() {
    if (eventCase_ == 1) {
       return (proto.RoomsInfoEvent) event_;
    }
    return proto.RoomsInfoEvent.getDefaultInstance();
  }

  public static final int ROOM_CREATED_FIELD_NUMBER = 2;
  /**
   * <code>optional .RoomCreatedEvent room_created = 2;</code>
   */
  public proto.RoomCreatedEvent getRoomCreated() {
    if (eventCase_ == 2) {
       return (proto.RoomCreatedEvent) event_;
    }
    return proto.RoomCreatedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomCreatedEvent room_created = 2;</code>
   */
  public proto.RoomCreatedEventOrBuilder getRoomCreatedOrBuilder() {
    if (eventCase_ == 2) {
       return (proto.RoomCreatedEvent) event_;
    }
    return proto.RoomCreatedEvent.getDefaultInstance();
  }

  public static final int ROOM_NOT_CREATED_FIELD_NUMBER = 3;
  /**
   * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
   */
  public proto.RoomNotCreatedEvent getRoomNotCreated() {
    if (eventCase_ == 3) {
       return (proto.RoomNotCreatedEvent) event_;
    }
    return proto.RoomNotCreatedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
   */
  public proto.RoomNotCreatedEventOrBuilder getRoomNotCreatedOrBuilder() {
    if (eventCase_ == 3) {
       return (proto.RoomNotCreatedEvent) event_;
    }
    return proto.RoomNotCreatedEvent.getDefaultInstance();
  }

  public static final int ROOM_JOINED_FIELD_NUMBER = 4;
  /**
   * <code>optional .RoomJoinedEvent room_joined = 4;</code>
   */
  public proto.RoomJoinedEvent getRoomJoined() {
    if (eventCase_ == 4) {
       return (proto.RoomJoinedEvent) event_;
    }
    return proto.RoomJoinedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomJoinedEvent room_joined = 4;</code>
   */
  public proto.RoomJoinedEventOrBuilder getRoomJoinedOrBuilder() {
    if (eventCase_ == 4) {
       return (proto.RoomJoinedEvent) event_;
    }
    return proto.RoomJoinedEvent.getDefaultInstance();
  }

  public static final int ROOM_NOT_JOINED_FIELD_NUMBER = 5;
  /**
   * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
   */
  public proto.RoomNotJoinedEvent getRoomNotJoined() {
    if (eventCase_ == 5) {
       return (proto.RoomNotJoinedEvent) event_;
    }
    return proto.RoomNotJoinedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
   */
  public proto.RoomNotJoinedEventOrBuilder getRoomNotJoinedOrBuilder() {
    if (eventCase_ == 5) {
       return (proto.RoomNotJoinedEvent) event_;
    }
    return proto.RoomNotJoinedEvent.getDefaultInstance();
  }

  public static final int ROOM_LEAVED_FIELD_NUMBER = 6;
  /**
   * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
   */
  public proto.RoomLeavedEvent getRoomLeaved() {
    if (eventCase_ == 6) {
       return (proto.RoomLeavedEvent) event_;
    }
    return proto.RoomLeavedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
   */
  public proto.RoomLeavedEventOrBuilder getRoomLeavedOrBuilder() {
    if (eventCase_ == 6) {
       return (proto.RoomLeavedEvent) event_;
    }
    return proto.RoomLeavedEvent.getDefaultInstance();
  }

  public static final int ROOM_NOT_LEAVED_FIELD_NUMBER = 7;
  /**
   * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
   */
  public proto.RoomNotLeavedEvent getRoomNotLeaved() {
    if (eventCase_ == 7) {
       return (proto.RoomNotLeavedEvent) event_;
    }
    return proto.RoomNotLeavedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
   */
  public proto.RoomNotLeavedEventOrBuilder getRoomNotLeavedOrBuilder() {
    if (eventCase_ == 7) {
       return (proto.RoomNotLeavedEvent) event_;
    }
    return proto.RoomNotLeavedEvent.getDefaultInstance();
  }

  public static final int ROOM_REMOVED_FIELD_NUMBER = 8;
  /**
   * <code>optional .RoomRemovedEvent room_removed = 8;</code>
   */
  public proto.RoomRemovedEvent getRoomRemoved() {
    if (eventCase_ == 8) {
       return (proto.RoomRemovedEvent) event_;
    }
    return proto.RoomRemovedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .RoomRemovedEvent room_removed = 8;</code>
   */
  public proto.RoomRemovedEventOrBuilder getRoomRemovedOrBuilder() {
    if (eventCase_ == 8) {
       return (proto.RoomRemovedEvent) event_;
    }
    return proto.RoomRemovedEvent.getDefaultInstance();
  }

  public static final int MESSAGE_RECEIVED_FIELD_NUMBER = 9;
  /**
   * <code>optional .MessageReceived message_received = 9;</code>
   */
  public proto.MessageReceived getMessageReceived() {
    if (eventCase_ == 9) {
       return (proto.MessageReceived) event_;
    }
    return proto.MessageReceived.getDefaultInstance();
  }
  /**
   * <code>optional .MessageReceived message_received = 9;</code>
   */
  public proto.MessageReceivedOrBuilder getMessageReceivedOrBuilder() {
    if (eventCase_ == 9) {
       return (proto.MessageReceived) event_;
    }
    return proto.MessageReceived.getDefaultInstance();
  }

  public static final int MESSAGE_SEND_FIELD_NUMBER = 10;
  /**
   * <code>optional .MessageSendEvent message_send = 10;</code>
   */
  public proto.MessageSendEvent getMessageSend() {
    if (eventCase_ == 10) {
       return (proto.MessageSendEvent) event_;
    }
    return proto.MessageSendEvent.getDefaultInstance();
  }
  /**
   * <code>optional .MessageSendEvent message_send = 10;</code>
   */
  public proto.MessageSendEventOrBuilder getMessageSendOrBuilder() {
    if (eventCase_ == 10) {
       return (proto.MessageSendEvent) event_;
    }
    return proto.MessageSendEvent.getDefaultInstance();
  }

  public static final int MESSAGE_NOT_SEND_FIELD_NUMBER = 11;
  /**
   * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
   */
  public proto.MessageNotSendEvent getMessageNotSend() {
    if (eventCase_ == 11) {
       return (proto.MessageNotSendEvent) event_;
    }
    return proto.MessageNotSendEvent.getDefaultInstance();
  }
  /**
   * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
   */
  public proto.MessageNotSendEventOrBuilder getMessageNotSendOrBuilder() {
    if (eventCase_ == 11) {
       return (proto.MessageNotSendEvent) event_;
    }
    return proto.MessageNotSendEvent.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (proto.RoomsInfoEvent) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (proto.RoomCreatedEvent) event_);
    }
    if (eventCase_ == 3) {
      output.writeMessage(3, (proto.RoomNotCreatedEvent) event_);
    }
    if (eventCase_ == 4) {
      output.writeMessage(4, (proto.RoomJoinedEvent) event_);
    }
    if (eventCase_ == 5) {
      output.writeMessage(5, (proto.RoomNotJoinedEvent) event_);
    }
    if (eventCase_ == 6) {
      output.writeMessage(6, (proto.RoomLeavedEvent) event_);
    }
    if (eventCase_ == 7) {
      output.writeMessage(7, (proto.RoomNotLeavedEvent) event_);
    }
    if (eventCase_ == 8) {
      output.writeMessage(8, (proto.RoomRemovedEvent) event_);
    }
    if (eventCase_ == 9) {
      output.writeMessage(9, (proto.MessageReceived) event_);
    }
    if (eventCase_ == 10) {
      output.writeMessage(10, (proto.MessageSendEvent) event_);
    }
    if (eventCase_ == 11) {
      output.writeMessage(11, (proto.MessageNotSendEvent) event_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (proto.RoomsInfoEvent) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (proto.RoomCreatedEvent) event_);
    }
    if (eventCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (proto.RoomNotCreatedEvent) event_);
    }
    if (eventCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (proto.RoomJoinedEvent) event_);
    }
    if (eventCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (proto.RoomNotJoinedEvent) event_);
    }
    if (eventCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (proto.RoomLeavedEvent) event_);
    }
    if (eventCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (proto.RoomNotLeavedEvent) event_);
    }
    if (eventCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (proto.RoomRemovedEvent) event_);
    }
    if (eventCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (proto.MessageReceived) event_);
    }
    if (eventCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (proto.MessageSendEvent) event_);
    }
    if (eventCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (proto.MessageNotSendEvent) event_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.SignalingEvent)) {
      return super.equals(obj);
    }
    proto.SignalingEvent other = (proto.SignalingEvent) obj;

    boolean result = true;
    result = result && getEventCase().equals(
        other.getEventCase());
    if (!result) return false;
    switch (eventCase_) {
      case 1:
        result = result && getRoomsInfo()
            .equals(other.getRoomsInfo());
        break;
      case 2:
        result = result && getRoomCreated()
            .equals(other.getRoomCreated());
        break;
      case 3:
        result = result && getRoomNotCreated()
            .equals(other.getRoomNotCreated());
        break;
      case 4:
        result = result && getRoomJoined()
            .equals(other.getRoomJoined());
        break;
      case 5:
        result = result && getRoomNotJoined()
            .equals(other.getRoomNotJoined());
        break;
      case 6:
        result = result && getRoomLeaved()
            .equals(other.getRoomLeaved());
        break;
      case 7:
        result = result && getRoomNotLeaved()
            .equals(other.getRoomNotLeaved());
        break;
      case 8:
        result = result && getRoomRemoved()
            .equals(other.getRoomRemoved());
        break;
      case 9:
        result = result && getMessageReceived()
            .equals(other.getMessageReceived());
        break;
      case 10:
        result = result && getMessageSend()
            .equals(other.getMessageSend());
        break;
      case 11:
        result = result && getMessageNotSend()
            .equals(other.getMessageNotSend());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + ROOMS_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getRoomsInfo().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ROOM_CREATED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomCreated().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ROOM_NOT_CREATED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomNotCreated().hashCode();
        break;
      case 4:
        hash = (37 * hash) + ROOM_JOINED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomJoined().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ROOM_NOT_JOINED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomNotJoined().hashCode();
        break;
      case 6:
        hash = (37 * hash) + ROOM_LEAVED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomLeaved().hashCode();
        break;
      case 7:
        hash = (37 * hash) + ROOM_NOT_LEAVED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomNotLeaved().hashCode();
        break;
      case 8:
        hash = (37 * hash) + ROOM_REMOVED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomRemoved().hashCode();
        break;
      case 9:
        hash = (37 * hash) + MESSAGE_RECEIVED_FIELD_NUMBER;
        hash = (53 * hash) + getMessageReceived().hashCode();
        break;
      case 10:
        hash = (37 * hash) + MESSAGE_SEND_FIELD_NUMBER;
        hash = (53 * hash) + getMessageSend().hashCode();
        break;
      case 11:
        hash = (37 * hash) + MESSAGE_NOT_SEND_FIELD_NUMBER;
        hash = (53 * hash) + getMessageNotSend().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.SignalingEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.SignalingEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.SignalingEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.SignalingEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.SignalingEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.SignalingEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.SignalingEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.SignalingEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.SignalingEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.SignalingEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.SignalingEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SignalingEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SignalingEvent)
      proto.SignalingEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Signaling.internal_static_SignalingEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Signaling.internal_static_SignalingEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SignalingEvent.class, proto.SignalingEvent.Builder.class);
    }

    // Construct using proto.SignalingEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Signaling.internal_static_SignalingEvent_descriptor;
    }

    public proto.SignalingEvent getDefaultInstanceForType() {
      return proto.SignalingEvent.getDefaultInstance();
    }

    public proto.SignalingEvent build() {
      proto.SignalingEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public proto.SignalingEvent buildPartial() {
      proto.SignalingEvent result = new proto.SignalingEvent(this);
      if (eventCase_ == 1) {
        if (roomsInfoBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomsInfoBuilder_.build();
        }
      }
      if (eventCase_ == 2) {
        if (roomCreatedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomCreatedBuilder_.build();
        }
      }
      if (eventCase_ == 3) {
        if (roomNotCreatedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomNotCreatedBuilder_.build();
        }
      }
      if (eventCase_ == 4) {
        if (roomJoinedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomJoinedBuilder_.build();
        }
      }
      if (eventCase_ == 5) {
        if (roomNotJoinedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomNotJoinedBuilder_.build();
        }
      }
      if (eventCase_ == 6) {
        if (roomLeavedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomLeavedBuilder_.build();
        }
      }
      if (eventCase_ == 7) {
        if (roomNotLeavedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomNotLeavedBuilder_.build();
        }
      }
      if (eventCase_ == 8) {
        if (roomRemovedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = roomRemovedBuilder_.build();
        }
      }
      if (eventCase_ == 9) {
        if (messageReceivedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = messageReceivedBuilder_.build();
        }
      }
      if (eventCase_ == 10) {
        if (messageSendBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = messageSendBuilder_.build();
        }
      }
      if (eventCase_ == 11) {
        if (messageNotSendBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = messageNotSendBuilder_.build();
        }
      }
      result.eventCase_ = eventCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.SignalingEvent) {
        return mergeFrom((proto.SignalingEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.SignalingEvent other) {
      if (other == proto.SignalingEvent.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case ROOMS_INFO: {
          mergeRoomsInfo(other.getRoomsInfo());
          break;
        }
        case ROOM_CREATED: {
          mergeRoomCreated(other.getRoomCreated());
          break;
        }
        case ROOM_NOT_CREATED: {
          mergeRoomNotCreated(other.getRoomNotCreated());
          break;
        }
        case ROOM_JOINED: {
          mergeRoomJoined(other.getRoomJoined());
          break;
        }
        case ROOM_NOT_JOINED: {
          mergeRoomNotJoined(other.getRoomNotJoined());
          break;
        }
        case ROOM_LEAVED: {
          mergeRoomLeaved(other.getRoomLeaved());
          break;
        }
        case ROOM_NOT_LEAVED: {
          mergeRoomNotLeaved(other.getRoomNotLeaved());
          break;
        }
        case ROOM_REMOVED: {
          mergeRoomRemoved(other.getRoomRemoved());
          break;
        }
        case MESSAGE_RECEIVED: {
          mergeMessageReceived(other.getMessageReceived());
          break;
        }
        case MESSAGE_SEND: {
          mergeMessageSend(other.getMessageSend());
          break;
        }
        case MESSAGE_NOT_SEND: {
          mergeMessageNotSend(other.getMessageNotSend());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.SignalingEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.SignalingEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomsInfoEvent, proto.RoomsInfoEvent.Builder, proto.RoomsInfoEventOrBuilder> roomsInfoBuilder_;
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    public proto.RoomsInfoEvent getRoomsInfo() {
      if (roomsInfoBuilder_ == null) {
        if (eventCase_ == 1) {
          return (proto.RoomsInfoEvent) event_;
        }
        return proto.RoomsInfoEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return roomsInfoBuilder_.getMessage();
        }
        return proto.RoomsInfoEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    public Builder setRoomsInfo(proto.RoomsInfoEvent value) {
      if (roomsInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomsInfoBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    public Builder setRoomsInfo(
        proto.RoomsInfoEvent.Builder builderForValue) {
      if (roomsInfoBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomsInfoBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    public Builder mergeRoomsInfo(proto.RoomsInfoEvent value) {
      if (roomsInfoBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != proto.RoomsInfoEvent.getDefaultInstance()) {
          event_ = proto.RoomsInfoEvent.newBuilder((proto.RoomsInfoEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          roomsInfoBuilder_.mergeFrom(value);
        }
        roomsInfoBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    public Builder clearRoomsInfo() {
      if (roomsInfoBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        roomsInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    public proto.RoomsInfoEvent.Builder getRoomsInfoBuilder() {
      return getRoomsInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    public proto.RoomsInfoEventOrBuilder getRoomsInfoOrBuilder() {
      if ((eventCase_ == 1) && (roomsInfoBuilder_ != null)) {
        return roomsInfoBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (proto.RoomsInfoEvent) event_;
        }
        return proto.RoomsInfoEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomsInfoEvent, proto.RoomsInfoEvent.Builder, proto.RoomsInfoEventOrBuilder> 
        getRoomsInfoFieldBuilder() {
      if (roomsInfoBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = proto.RoomsInfoEvent.getDefaultInstance();
        }
        roomsInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomsInfoEvent, proto.RoomsInfoEvent.Builder, proto.RoomsInfoEventOrBuilder>(
                (proto.RoomsInfoEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();;
      return roomsInfoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomCreatedEvent, proto.RoomCreatedEvent.Builder, proto.RoomCreatedEventOrBuilder> roomCreatedBuilder_;
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    public proto.RoomCreatedEvent getRoomCreated() {
      if (roomCreatedBuilder_ == null) {
        if (eventCase_ == 2) {
          return (proto.RoomCreatedEvent) event_;
        }
        return proto.RoomCreatedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return roomCreatedBuilder_.getMessage();
        }
        return proto.RoomCreatedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    public Builder setRoomCreated(proto.RoomCreatedEvent value) {
      if (roomCreatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomCreatedBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    public Builder setRoomCreated(
        proto.RoomCreatedEvent.Builder builderForValue) {
      if (roomCreatedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomCreatedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    public Builder mergeRoomCreated(proto.RoomCreatedEvent value) {
      if (roomCreatedBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != proto.RoomCreatedEvent.getDefaultInstance()) {
          event_ = proto.RoomCreatedEvent.newBuilder((proto.RoomCreatedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          roomCreatedBuilder_.mergeFrom(value);
        }
        roomCreatedBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    public Builder clearRoomCreated() {
      if (roomCreatedBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        roomCreatedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    public proto.RoomCreatedEvent.Builder getRoomCreatedBuilder() {
      return getRoomCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    public proto.RoomCreatedEventOrBuilder getRoomCreatedOrBuilder() {
      if ((eventCase_ == 2) && (roomCreatedBuilder_ != null)) {
        return roomCreatedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (proto.RoomCreatedEvent) event_;
        }
        return proto.RoomCreatedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomCreatedEvent room_created = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomCreatedEvent, proto.RoomCreatedEvent.Builder, proto.RoomCreatedEventOrBuilder> 
        getRoomCreatedFieldBuilder() {
      if (roomCreatedBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = proto.RoomCreatedEvent.getDefaultInstance();
        }
        roomCreatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomCreatedEvent, proto.RoomCreatedEvent.Builder, proto.RoomCreatedEventOrBuilder>(
                (proto.RoomCreatedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();;
      return roomCreatedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomNotCreatedEvent, proto.RoomNotCreatedEvent.Builder, proto.RoomNotCreatedEventOrBuilder> roomNotCreatedBuilder_;
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    public proto.RoomNotCreatedEvent getRoomNotCreated() {
      if (roomNotCreatedBuilder_ == null) {
        if (eventCase_ == 3) {
          return (proto.RoomNotCreatedEvent) event_;
        }
        return proto.RoomNotCreatedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 3) {
          return roomNotCreatedBuilder_.getMessage();
        }
        return proto.RoomNotCreatedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    public Builder setRoomNotCreated(proto.RoomNotCreatedEvent value) {
      if (roomNotCreatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomNotCreatedBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    public Builder setRoomNotCreated(
        proto.RoomNotCreatedEvent.Builder builderForValue) {
      if (roomNotCreatedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomNotCreatedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    public Builder mergeRoomNotCreated(proto.RoomNotCreatedEvent value) {
      if (roomNotCreatedBuilder_ == null) {
        if (eventCase_ == 3 &&
            event_ != proto.RoomNotCreatedEvent.getDefaultInstance()) {
          event_ = proto.RoomNotCreatedEvent.newBuilder((proto.RoomNotCreatedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 3) {
          roomNotCreatedBuilder_.mergeFrom(value);
        }
        roomNotCreatedBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    public Builder clearRoomNotCreated() {
      if (roomNotCreatedBuilder_ == null) {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
        }
        roomNotCreatedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    public proto.RoomNotCreatedEvent.Builder getRoomNotCreatedBuilder() {
      return getRoomNotCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    public proto.RoomNotCreatedEventOrBuilder getRoomNotCreatedOrBuilder() {
      if ((eventCase_ == 3) && (roomNotCreatedBuilder_ != null)) {
        return roomNotCreatedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 3) {
          return (proto.RoomNotCreatedEvent) event_;
        }
        return proto.RoomNotCreatedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomNotCreatedEvent, proto.RoomNotCreatedEvent.Builder, proto.RoomNotCreatedEventOrBuilder> 
        getRoomNotCreatedFieldBuilder() {
      if (roomNotCreatedBuilder_ == null) {
        if (!(eventCase_ == 3)) {
          event_ = proto.RoomNotCreatedEvent.getDefaultInstance();
        }
        roomNotCreatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomNotCreatedEvent, proto.RoomNotCreatedEvent.Builder, proto.RoomNotCreatedEventOrBuilder>(
                (proto.RoomNotCreatedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 3;
      onChanged();;
      return roomNotCreatedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomJoinedEvent, proto.RoomJoinedEvent.Builder, proto.RoomJoinedEventOrBuilder> roomJoinedBuilder_;
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    public proto.RoomJoinedEvent getRoomJoined() {
      if (roomJoinedBuilder_ == null) {
        if (eventCase_ == 4) {
          return (proto.RoomJoinedEvent) event_;
        }
        return proto.RoomJoinedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 4) {
          return roomJoinedBuilder_.getMessage();
        }
        return proto.RoomJoinedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    public Builder setRoomJoined(proto.RoomJoinedEvent value) {
      if (roomJoinedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomJoinedBuilder_.setMessage(value);
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    public Builder setRoomJoined(
        proto.RoomJoinedEvent.Builder builderForValue) {
      if (roomJoinedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomJoinedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    public Builder mergeRoomJoined(proto.RoomJoinedEvent value) {
      if (roomJoinedBuilder_ == null) {
        if (eventCase_ == 4 &&
            event_ != proto.RoomJoinedEvent.getDefaultInstance()) {
          event_ = proto.RoomJoinedEvent.newBuilder((proto.RoomJoinedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 4) {
          roomJoinedBuilder_.mergeFrom(value);
        }
        roomJoinedBuilder_.setMessage(value);
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    public Builder clearRoomJoined() {
      if (roomJoinedBuilder_ == null) {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
        }
        roomJoinedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    public proto.RoomJoinedEvent.Builder getRoomJoinedBuilder() {
      return getRoomJoinedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    public proto.RoomJoinedEventOrBuilder getRoomJoinedOrBuilder() {
      if ((eventCase_ == 4) && (roomJoinedBuilder_ != null)) {
        return roomJoinedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 4) {
          return (proto.RoomJoinedEvent) event_;
        }
        return proto.RoomJoinedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomJoinedEvent room_joined = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomJoinedEvent, proto.RoomJoinedEvent.Builder, proto.RoomJoinedEventOrBuilder> 
        getRoomJoinedFieldBuilder() {
      if (roomJoinedBuilder_ == null) {
        if (!(eventCase_ == 4)) {
          event_ = proto.RoomJoinedEvent.getDefaultInstance();
        }
        roomJoinedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomJoinedEvent, proto.RoomJoinedEvent.Builder, proto.RoomJoinedEventOrBuilder>(
                (proto.RoomJoinedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 4;
      onChanged();;
      return roomJoinedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomNotJoinedEvent, proto.RoomNotJoinedEvent.Builder, proto.RoomNotJoinedEventOrBuilder> roomNotJoinedBuilder_;
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    public proto.RoomNotJoinedEvent getRoomNotJoined() {
      if (roomNotJoinedBuilder_ == null) {
        if (eventCase_ == 5) {
          return (proto.RoomNotJoinedEvent) event_;
        }
        return proto.RoomNotJoinedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 5) {
          return roomNotJoinedBuilder_.getMessage();
        }
        return proto.RoomNotJoinedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    public Builder setRoomNotJoined(proto.RoomNotJoinedEvent value) {
      if (roomNotJoinedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomNotJoinedBuilder_.setMessage(value);
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    public Builder setRoomNotJoined(
        proto.RoomNotJoinedEvent.Builder builderForValue) {
      if (roomNotJoinedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomNotJoinedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    public Builder mergeRoomNotJoined(proto.RoomNotJoinedEvent value) {
      if (roomNotJoinedBuilder_ == null) {
        if (eventCase_ == 5 &&
            event_ != proto.RoomNotJoinedEvent.getDefaultInstance()) {
          event_ = proto.RoomNotJoinedEvent.newBuilder((proto.RoomNotJoinedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 5) {
          roomNotJoinedBuilder_.mergeFrom(value);
        }
        roomNotJoinedBuilder_.setMessage(value);
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    public Builder clearRoomNotJoined() {
      if (roomNotJoinedBuilder_ == null) {
        if (eventCase_ == 5) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 5) {
          eventCase_ = 0;
          event_ = null;
        }
        roomNotJoinedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    public proto.RoomNotJoinedEvent.Builder getRoomNotJoinedBuilder() {
      return getRoomNotJoinedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    public proto.RoomNotJoinedEventOrBuilder getRoomNotJoinedOrBuilder() {
      if ((eventCase_ == 5) && (roomNotJoinedBuilder_ != null)) {
        return roomNotJoinedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 5) {
          return (proto.RoomNotJoinedEvent) event_;
        }
        return proto.RoomNotJoinedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomNotJoinedEvent, proto.RoomNotJoinedEvent.Builder, proto.RoomNotJoinedEventOrBuilder> 
        getRoomNotJoinedFieldBuilder() {
      if (roomNotJoinedBuilder_ == null) {
        if (!(eventCase_ == 5)) {
          event_ = proto.RoomNotJoinedEvent.getDefaultInstance();
        }
        roomNotJoinedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomNotJoinedEvent, proto.RoomNotJoinedEvent.Builder, proto.RoomNotJoinedEventOrBuilder>(
                (proto.RoomNotJoinedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 5;
      onChanged();;
      return roomNotJoinedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomLeavedEvent, proto.RoomLeavedEvent.Builder, proto.RoomLeavedEventOrBuilder> roomLeavedBuilder_;
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    public proto.RoomLeavedEvent getRoomLeaved() {
      if (roomLeavedBuilder_ == null) {
        if (eventCase_ == 6) {
          return (proto.RoomLeavedEvent) event_;
        }
        return proto.RoomLeavedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 6) {
          return roomLeavedBuilder_.getMessage();
        }
        return proto.RoomLeavedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    public Builder setRoomLeaved(proto.RoomLeavedEvent value) {
      if (roomLeavedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomLeavedBuilder_.setMessage(value);
      }
      eventCase_ = 6;
      return this;
    }
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    public Builder setRoomLeaved(
        proto.RoomLeavedEvent.Builder builderForValue) {
      if (roomLeavedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomLeavedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 6;
      return this;
    }
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    public Builder mergeRoomLeaved(proto.RoomLeavedEvent value) {
      if (roomLeavedBuilder_ == null) {
        if (eventCase_ == 6 &&
            event_ != proto.RoomLeavedEvent.getDefaultInstance()) {
          event_ = proto.RoomLeavedEvent.newBuilder((proto.RoomLeavedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 6) {
          roomLeavedBuilder_.mergeFrom(value);
        }
        roomLeavedBuilder_.setMessage(value);
      }
      eventCase_ = 6;
      return this;
    }
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    public Builder clearRoomLeaved() {
      if (roomLeavedBuilder_ == null) {
        if (eventCase_ == 6) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 6) {
          eventCase_ = 0;
          event_ = null;
        }
        roomLeavedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    public proto.RoomLeavedEvent.Builder getRoomLeavedBuilder() {
      return getRoomLeavedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    public proto.RoomLeavedEventOrBuilder getRoomLeavedOrBuilder() {
      if ((eventCase_ == 6) && (roomLeavedBuilder_ != null)) {
        return roomLeavedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 6) {
          return (proto.RoomLeavedEvent) event_;
        }
        return proto.RoomLeavedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomLeavedEvent, proto.RoomLeavedEvent.Builder, proto.RoomLeavedEventOrBuilder> 
        getRoomLeavedFieldBuilder() {
      if (roomLeavedBuilder_ == null) {
        if (!(eventCase_ == 6)) {
          event_ = proto.RoomLeavedEvent.getDefaultInstance();
        }
        roomLeavedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomLeavedEvent, proto.RoomLeavedEvent.Builder, proto.RoomLeavedEventOrBuilder>(
                (proto.RoomLeavedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 6;
      onChanged();;
      return roomLeavedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomNotLeavedEvent, proto.RoomNotLeavedEvent.Builder, proto.RoomNotLeavedEventOrBuilder> roomNotLeavedBuilder_;
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    public proto.RoomNotLeavedEvent getRoomNotLeaved() {
      if (roomNotLeavedBuilder_ == null) {
        if (eventCase_ == 7) {
          return (proto.RoomNotLeavedEvent) event_;
        }
        return proto.RoomNotLeavedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 7) {
          return roomNotLeavedBuilder_.getMessage();
        }
        return proto.RoomNotLeavedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    public Builder setRoomNotLeaved(proto.RoomNotLeavedEvent value) {
      if (roomNotLeavedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomNotLeavedBuilder_.setMessage(value);
      }
      eventCase_ = 7;
      return this;
    }
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    public Builder setRoomNotLeaved(
        proto.RoomNotLeavedEvent.Builder builderForValue) {
      if (roomNotLeavedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomNotLeavedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 7;
      return this;
    }
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    public Builder mergeRoomNotLeaved(proto.RoomNotLeavedEvent value) {
      if (roomNotLeavedBuilder_ == null) {
        if (eventCase_ == 7 &&
            event_ != proto.RoomNotLeavedEvent.getDefaultInstance()) {
          event_ = proto.RoomNotLeavedEvent.newBuilder((proto.RoomNotLeavedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 7) {
          roomNotLeavedBuilder_.mergeFrom(value);
        }
        roomNotLeavedBuilder_.setMessage(value);
      }
      eventCase_ = 7;
      return this;
    }
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    public Builder clearRoomNotLeaved() {
      if (roomNotLeavedBuilder_ == null) {
        if (eventCase_ == 7) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 7) {
          eventCase_ = 0;
          event_ = null;
        }
        roomNotLeavedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    public proto.RoomNotLeavedEvent.Builder getRoomNotLeavedBuilder() {
      return getRoomNotLeavedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    public proto.RoomNotLeavedEventOrBuilder getRoomNotLeavedOrBuilder() {
      if ((eventCase_ == 7) && (roomNotLeavedBuilder_ != null)) {
        return roomNotLeavedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 7) {
          return (proto.RoomNotLeavedEvent) event_;
        }
        return proto.RoomNotLeavedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomNotLeavedEvent, proto.RoomNotLeavedEvent.Builder, proto.RoomNotLeavedEventOrBuilder> 
        getRoomNotLeavedFieldBuilder() {
      if (roomNotLeavedBuilder_ == null) {
        if (!(eventCase_ == 7)) {
          event_ = proto.RoomNotLeavedEvent.getDefaultInstance();
        }
        roomNotLeavedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomNotLeavedEvent, proto.RoomNotLeavedEvent.Builder, proto.RoomNotLeavedEventOrBuilder>(
                (proto.RoomNotLeavedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 7;
      onChanged();;
      return roomNotLeavedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomRemovedEvent, proto.RoomRemovedEvent.Builder, proto.RoomRemovedEventOrBuilder> roomRemovedBuilder_;
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    public proto.RoomRemovedEvent getRoomRemoved() {
      if (roomRemovedBuilder_ == null) {
        if (eventCase_ == 8) {
          return (proto.RoomRemovedEvent) event_;
        }
        return proto.RoomRemovedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 8) {
          return roomRemovedBuilder_.getMessage();
        }
        return proto.RoomRemovedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    public Builder setRoomRemoved(proto.RoomRemovedEvent value) {
      if (roomRemovedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomRemovedBuilder_.setMessage(value);
      }
      eventCase_ = 8;
      return this;
    }
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    public Builder setRoomRemoved(
        proto.RoomRemovedEvent.Builder builderForValue) {
      if (roomRemovedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomRemovedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 8;
      return this;
    }
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    public Builder mergeRoomRemoved(proto.RoomRemovedEvent value) {
      if (roomRemovedBuilder_ == null) {
        if (eventCase_ == 8 &&
            event_ != proto.RoomRemovedEvent.getDefaultInstance()) {
          event_ = proto.RoomRemovedEvent.newBuilder((proto.RoomRemovedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 8) {
          roomRemovedBuilder_.mergeFrom(value);
        }
        roomRemovedBuilder_.setMessage(value);
      }
      eventCase_ = 8;
      return this;
    }
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    public Builder clearRoomRemoved() {
      if (roomRemovedBuilder_ == null) {
        if (eventCase_ == 8) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 8) {
          eventCase_ = 0;
          event_ = null;
        }
        roomRemovedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    public proto.RoomRemovedEvent.Builder getRoomRemovedBuilder() {
      return getRoomRemovedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    public proto.RoomRemovedEventOrBuilder getRoomRemovedOrBuilder() {
      if ((eventCase_ == 8) && (roomRemovedBuilder_ != null)) {
        return roomRemovedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 8) {
          return (proto.RoomRemovedEvent) event_;
        }
        return proto.RoomRemovedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RoomRemovedEvent room_removed = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.RoomRemovedEvent, proto.RoomRemovedEvent.Builder, proto.RoomRemovedEventOrBuilder> 
        getRoomRemovedFieldBuilder() {
      if (roomRemovedBuilder_ == null) {
        if (!(eventCase_ == 8)) {
          event_ = proto.RoomRemovedEvent.getDefaultInstance();
        }
        roomRemovedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.RoomRemovedEvent, proto.RoomRemovedEvent.Builder, proto.RoomRemovedEventOrBuilder>(
                (proto.RoomRemovedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 8;
      onChanged();;
      return roomRemovedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.MessageReceived, proto.MessageReceived.Builder, proto.MessageReceivedOrBuilder> messageReceivedBuilder_;
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    public proto.MessageReceived getMessageReceived() {
      if (messageReceivedBuilder_ == null) {
        if (eventCase_ == 9) {
          return (proto.MessageReceived) event_;
        }
        return proto.MessageReceived.getDefaultInstance();
      } else {
        if (eventCase_ == 9) {
          return messageReceivedBuilder_.getMessage();
        }
        return proto.MessageReceived.getDefaultInstance();
      }
    }
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    public Builder setMessageReceived(proto.MessageReceived value) {
      if (messageReceivedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        messageReceivedBuilder_.setMessage(value);
      }
      eventCase_ = 9;
      return this;
    }
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    public Builder setMessageReceived(
        proto.MessageReceived.Builder builderForValue) {
      if (messageReceivedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        messageReceivedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 9;
      return this;
    }
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    public Builder mergeMessageReceived(proto.MessageReceived value) {
      if (messageReceivedBuilder_ == null) {
        if (eventCase_ == 9 &&
            event_ != proto.MessageReceived.getDefaultInstance()) {
          event_ = proto.MessageReceived.newBuilder((proto.MessageReceived) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 9) {
          messageReceivedBuilder_.mergeFrom(value);
        }
        messageReceivedBuilder_.setMessage(value);
      }
      eventCase_ = 9;
      return this;
    }
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    public Builder clearMessageReceived() {
      if (messageReceivedBuilder_ == null) {
        if (eventCase_ == 9) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 9) {
          eventCase_ = 0;
          event_ = null;
        }
        messageReceivedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    public proto.MessageReceived.Builder getMessageReceivedBuilder() {
      return getMessageReceivedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    public proto.MessageReceivedOrBuilder getMessageReceivedOrBuilder() {
      if ((eventCase_ == 9) && (messageReceivedBuilder_ != null)) {
        return messageReceivedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 9) {
          return (proto.MessageReceived) event_;
        }
        return proto.MessageReceived.getDefaultInstance();
      }
    }
    /**
     * <code>optional .MessageReceived message_received = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.MessageReceived, proto.MessageReceived.Builder, proto.MessageReceivedOrBuilder> 
        getMessageReceivedFieldBuilder() {
      if (messageReceivedBuilder_ == null) {
        if (!(eventCase_ == 9)) {
          event_ = proto.MessageReceived.getDefaultInstance();
        }
        messageReceivedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.MessageReceived, proto.MessageReceived.Builder, proto.MessageReceivedOrBuilder>(
                (proto.MessageReceived) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 9;
      onChanged();;
      return messageReceivedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.MessageSendEvent, proto.MessageSendEvent.Builder, proto.MessageSendEventOrBuilder> messageSendBuilder_;
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    public proto.MessageSendEvent getMessageSend() {
      if (messageSendBuilder_ == null) {
        if (eventCase_ == 10) {
          return (proto.MessageSendEvent) event_;
        }
        return proto.MessageSendEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 10) {
          return messageSendBuilder_.getMessage();
        }
        return proto.MessageSendEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    public Builder setMessageSend(proto.MessageSendEvent value) {
      if (messageSendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        messageSendBuilder_.setMessage(value);
      }
      eventCase_ = 10;
      return this;
    }
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    public Builder setMessageSend(
        proto.MessageSendEvent.Builder builderForValue) {
      if (messageSendBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        messageSendBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 10;
      return this;
    }
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    public Builder mergeMessageSend(proto.MessageSendEvent value) {
      if (messageSendBuilder_ == null) {
        if (eventCase_ == 10 &&
            event_ != proto.MessageSendEvent.getDefaultInstance()) {
          event_ = proto.MessageSendEvent.newBuilder((proto.MessageSendEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 10) {
          messageSendBuilder_.mergeFrom(value);
        }
        messageSendBuilder_.setMessage(value);
      }
      eventCase_ = 10;
      return this;
    }
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    public Builder clearMessageSend() {
      if (messageSendBuilder_ == null) {
        if (eventCase_ == 10) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 10) {
          eventCase_ = 0;
          event_ = null;
        }
        messageSendBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    public proto.MessageSendEvent.Builder getMessageSendBuilder() {
      return getMessageSendFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    public proto.MessageSendEventOrBuilder getMessageSendOrBuilder() {
      if ((eventCase_ == 10) && (messageSendBuilder_ != null)) {
        return messageSendBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 10) {
          return (proto.MessageSendEvent) event_;
        }
        return proto.MessageSendEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .MessageSendEvent message_send = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.MessageSendEvent, proto.MessageSendEvent.Builder, proto.MessageSendEventOrBuilder> 
        getMessageSendFieldBuilder() {
      if (messageSendBuilder_ == null) {
        if (!(eventCase_ == 10)) {
          event_ = proto.MessageSendEvent.getDefaultInstance();
        }
        messageSendBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.MessageSendEvent, proto.MessageSendEvent.Builder, proto.MessageSendEventOrBuilder>(
                (proto.MessageSendEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 10;
      onChanged();;
      return messageSendBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.MessageNotSendEvent, proto.MessageNotSendEvent.Builder, proto.MessageNotSendEventOrBuilder> messageNotSendBuilder_;
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    public proto.MessageNotSendEvent getMessageNotSend() {
      if (messageNotSendBuilder_ == null) {
        if (eventCase_ == 11) {
          return (proto.MessageNotSendEvent) event_;
        }
        return proto.MessageNotSendEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 11) {
          return messageNotSendBuilder_.getMessage();
        }
        return proto.MessageNotSendEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    public Builder setMessageNotSend(proto.MessageNotSendEvent value) {
      if (messageNotSendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        messageNotSendBuilder_.setMessage(value);
      }
      eventCase_ = 11;
      return this;
    }
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    public Builder setMessageNotSend(
        proto.MessageNotSendEvent.Builder builderForValue) {
      if (messageNotSendBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        messageNotSendBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 11;
      return this;
    }
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    public Builder mergeMessageNotSend(proto.MessageNotSendEvent value) {
      if (messageNotSendBuilder_ == null) {
        if (eventCase_ == 11 &&
            event_ != proto.MessageNotSendEvent.getDefaultInstance()) {
          event_ = proto.MessageNotSendEvent.newBuilder((proto.MessageNotSendEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 11) {
          messageNotSendBuilder_.mergeFrom(value);
        }
        messageNotSendBuilder_.setMessage(value);
      }
      eventCase_ = 11;
      return this;
    }
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    public Builder clearMessageNotSend() {
      if (messageNotSendBuilder_ == null) {
        if (eventCase_ == 11) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 11) {
          eventCase_ = 0;
          event_ = null;
        }
        messageNotSendBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    public proto.MessageNotSendEvent.Builder getMessageNotSendBuilder() {
      return getMessageNotSendFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    public proto.MessageNotSendEventOrBuilder getMessageNotSendOrBuilder() {
      if ((eventCase_ == 11) && (messageNotSendBuilder_ != null)) {
        return messageNotSendBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 11) {
          return (proto.MessageNotSendEvent) event_;
        }
        return proto.MessageNotSendEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.MessageNotSendEvent, proto.MessageNotSendEvent.Builder, proto.MessageNotSendEventOrBuilder> 
        getMessageNotSendFieldBuilder() {
      if (messageNotSendBuilder_ == null) {
        if (!(eventCase_ == 11)) {
          event_ = proto.MessageNotSendEvent.getDefaultInstance();
        }
        messageNotSendBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.MessageNotSendEvent, proto.MessageNotSendEvent.Builder, proto.MessageNotSendEventOrBuilder>(
                (proto.MessageNotSendEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 11;
      onChanged();;
      return messageNotSendBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:SignalingEvent)
  }

  // @@protoc_insertion_point(class_scope:SignalingEvent)
  private static final proto.SignalingEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.SignalingEvent();
  }

  public static proto.SignalingEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SignalingEvent>
      PARSER = new com.google.protobuf.AbstractParser<SignalingEvent>() {
    public SignalingEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignalingEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SignalingEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignalingEvent> getParserForType() {
    return PARSER;
  }

  public proto.SignalingEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

