// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

package proto;

public interface SignalingEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignalingEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
   */
  proto.RoomsInfoEvent getRoomsInfo();
  /**
   * <code>optional .RoomsInfoEvent rooms_info = 1;</code>
   */
  proto.RoomsInfoEventOrBuilder getRoomsInfoOrBuilder();

  /**
   * <code>optional .RoomCreatedEvent room_created = 2;</code>
   */
  proto.RoomCreatedEvent getRoomCreated();
  /**
   * <code>optional .RoomCreatedEvent room_created = 2;</code>
   */
  proto.RoomCreatedEventOrBuilder getRoomCreatedOrBuilder();

  /**
   * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
   */
  proto.RoomNotCreatedEvent getRoomNotCreated();
  /**
   * <code>optional .RoomNotCreatedEvent room_not_created = 3;</code>
   */
  proto.RoomNotCreatedEventOrBuilder getRoomNotCreatedOrBuilder();

  /**
   * <code>optional .RoomJoinedEvent room_joined = 4;</code>
   */
  proto.RoomJoinedEvent getRoomJoined();
  /**
   * <code>optional .RoomJoinedEvent room_joined = 4;</code>
   */
  proto.RoomJoinedEventOrBuilder getRoomJoinedOrBuilder();

  /**
   * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
   */
  proto.RoomNotJoinedEvent getRoomNotJoined();
  /**
   * <code>optional .RoomNotJoinedEvent room_not_joined = 5;</code>
   */
  proto.RoomNotJoinedEventOrBuilder getRoomNotJoinedOrBuilder();

  /**
   * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
   */
  proto.RoomLeavedEvent getRoomLeaved();
  /**
   * <code>optional .RoomLeavedEvent room_leaved = 6;</code>
   */
  proto.RoomLeavedEventOrBuilder getRoomLeavedOrBuilder();

  /**
   * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
   */
  proto.RoomNotLeavedEvent getRoomNotLeaved();
  /**
   * <code>optional .RoomNotLeavedEvent room_not_leaved = 7;</code>
   */
  proto.RoomNotLeavedEventOrBuilder getRoomNotLeavedOrBuilder();

  /**
   * <code>optional .RoomRemovedEvent room_removed = 8;</code>
   */
  proto.RoomRemovedEvent getRoomRemoved();
  /**
   * <code>optional .RoomRemovedEvent room_removed = 8;</code>
   */
  proto.RoomRemovedEventOrBuilder getRoomRemovedOrBuilder();

  /**
   * <code>optional .MessageReceived message_received = 9;</code>
   */
  proto.MessageReceived getMessageReceived();
  /**
   * <code>optional .MessageReceived message_received = 9;</code>
   */
  proto.MessageReceivedOrBuilder getMessageReceivedOrBuilder();

  /**
   * <code>optional .MessageSendEvent message_send = 10;</code>
   */
  proto.MessageSendEvent getMessageSend();
  /**
   * <code>optional .MessageSendEvent message_send = 10;</code>
   */
  proto.MessageSendEventOrBuilder getMessageSendOrBuilder();

  /**
   * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
   */
  proto.MessageNotSendEvent getMessageNotSend();
  /**
   * <code>optional .MessageNotSendEvent message_not_send = 11;</code>
   */
  proto.MessageNotSendEventOrBuilder getMessageNotSendOrBuilder();

  public proto.SignalingEvent.EventCase getEventCase();
}
