// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws.proto

package proto;

/**
 * Protobuf type {@code WsEvent}
 */
public  final class WsEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WsEvent)
    WsEventOrBuilder {
  // Use WsEvent.newBuilder() to construct.
  private WsEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WsEvent() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private WsEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            proto.InvitationEvent.Builder subBuilder = null;
            if (eventCase_ == 1) {
              subBuilder = ((proto.InvitationEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.InvitationEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.InvitationEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 1;
            break;
          }
          case 18: {
            proto.InvitationAcceptedEvent.Builder subBuilder = null;
            if (eventCase_ == 2) {
              subBuilder = ((proto.InvitationAcceptedEvent) event_).toBuilder();
            }
            event_ =
                input.readMessage(proto.InvitationAcceptedEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((proto.InvitationAcceptedEvent) event_);
              event_ = subBuilder.buildPartial();
            }
            eventCase_ = 2;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Ws.internal_static_WsEvent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Ws.internal_static_WsEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.WsEvent.class, proto.WsEvent.Builder.class);
  }

  private int eventCase_ = 0;
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite {
    INVITATION(1),
    INVITATION_ACCEPTED(2),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return INVITATION;
        case 2: return INVITATION_ACCEPTED;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int INVITATION_FIELD_NUMBER = 1;
  /**
   * <code>optional .InvitationEvent invitation = 1;</code>
   */
  public proto.InvitationEvent getInvitation() {
    if (eventCase_ == 1) {
       return (proto.InvitationEvent) event_;
    }
    return proto.InvitationEvent.getDefaultInstance();
  }
  /**
   * <code>optional .InvitationEvent invitation = 1;</code>
   */
  public proto.InvitationEventOrBuilder getInvitationOrBuilder() {
    if (eventCase_ == 1) {
       return (proto.InvitationEvent) event_;
    }
    return proto.InvitationEvent.getDefaultInstance();
  }

  public static final int INVITATION_ACCEPTED_FIELD_NUMBER = 2;
  /**
   * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
   */
  public proto.InvitationAcceptedEvent getInvitationAccepted() {
    if (eventCase_ == 2) {
       return (proto.InvitationAcceptedEvent) event_;
    }
    return proto.InvitationAcceptedEvent.getDefaultInstance();
  }
  /**
   * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
   */
  public proto.InvitationAcceptedEventOrBuilder getInvitationAcceptedOrBuilder() {
    if (eventCase_ == 2) {
       return (proto.InvitationAcceptedEvent) event_;
    }
    return proto.InvitationAcceptedEvent.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (proto.InvitationEvent) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (proto.InvitationAcceptedEvent) event_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (proto.InvitationEvent) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (proto.InvitationAcceptedEvent) event_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.WsEvent)) {
      return super.equals(obj);
    }
    proto.WsEvent other = (proto.WsEvent) obj;

    boolean result = true;
    result = result && getEventCase().equals(
        other.getEventCase());
    if (!result) return false;
    switch (eventCase_) {
      case 1:
        result = result && getInvitation()
            .equals(other.getInvitation());
        break;
      case 2:
        result = result && getInvitationAccepted()
            .equals(other.getInvitationAccepted());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + INVITATION_FIELD_NUMBER;
        hash = (53 * hash) + getInvitation().hashCode();
        break;
      case 2:
        hash = (37 * hash) + INVITATION_ACCEPTED_FIELD_NUMBER;
        hash = (53 * hash) + getInvitationAccepted().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.WsEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.WsEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.WsEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.WsEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.WsEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.WsEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.WsEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.WsEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.WsEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.WsEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.WsEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WsEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WsEvent)
      proto.WsEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Ws.internal_static_WsEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Ws.internal_static_WsEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.WsEvent.class, proto.WsEvent.Builder.class);
    }

    // Construct using proto.WsEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Ws.internal_static_WsEvent_descriptor;
    }

    public proto.WsEvent getDefaultInstanceForType() {
      return proto.WsEvent.getDefaultInstance();
    }

    public proto.WsEvent build() {
      proto.WsEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public proto.WsEvent buildPartial() {
      proto.WsEvent result = new proto.WsEvent(this);
      if (eventCase_ == 1) {
        if (invitationBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = invitationBuilder_.build();
        }
      }
      if (eventCase_ == 2) {
        if (invitationAcceptedBuilder_ == null) {
          result.event_ = event_;
        } else {
          result.event_ = invitationAcceptedBuilder_.build();
        }
      }
      result.eventCase_ = eventCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.WsEvent) {
        return mergeFrom((proto.WsEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.WsEvent other) {
      if (other == proto.WsEvent.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case INVITATION: {
          mergeInvitation(other.getInvitation());
          break;
        }
        case INVITATION_ACCEPTED: {
          mergeInvitationAccepted(other.getInvitationAccepted());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.WsEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.WsEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        proto.InvitationEvent, proto.InvitationEvent.Builder, proto.InvitationEventOrBuilder> invitationBuilder_;
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    public proto.InvitationEvent getInvitation() {
      if (invitationBuilder_ == null) {
        if (eventCase_ == 1) {
          return (proto.InvitationEvent) event_;
        }
        return proto.InvitationEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return invitationBuilder_.getMessage();
        }
        return proto.InvitationEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    public Builder setInvitation(proto.InvitationEvent value) {
      if (invitationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        invitationBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    public Builder setInvitation(
        proto.InvitationEvent.Builder builderForValue) {
      if (invitationBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        invitationBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    public Builder mergeInvitation(proto.InvitationEvent value) {
      if (invitationBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != proto.InvitationEvent.getDefaultInstance()) {
          event_ = proto.InvitationEvent.newBuilder((proto.InvitationEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          invitationBuilder_.mergeFrom(value);
        }
        invitationBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    public Builder clearInvitation() {
      if (invitationBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        invitationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    public proto.InvitationEvent.Builder getInvitationBuilder() {
      return getInvitationFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    public proto.InvitationEventOrBuilder getInvitationOrBuilder() {
      if ((eventCase_ == 1) && (invitationBuilder_ != null)) {
        return invitationBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (proto.InvitationEvent) event_;
        }
        return proto.InvitationEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .InvitationEvent invitation = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.InvitationEvent, proto.InvitationEvent.Builder, proto.InvitationEventOrBuilder> 
        getInvitationFieldBuilder() {
      if (invitationBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = proto.InvitationEvent.getDefaultInstance();
        }
        invitationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.InvitationEvent, proto.InvitationEvent.Builder, proto.InvitationEventOrBuilder>(
                (proto.InvitationEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();;
      return invitationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        proto.InvitationAcceptedEvent, proto.InvitationAcceptedEvent.Builder, proto.InvitationAcceptedEventOrBuilder> invitationAcceptedBuilder_;
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    public proto.InvitationAcceptedEvent getInvitationAccepted() {
      if (invitationAcceptedBuilder_ == null) {
        if (eventCase_ == 2) {
          return (proto.InvitationAcceptedEvent) event_;
        }
        return proto.InvitationAcceptedEvent.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return invitationAcceptedBuilder_.getMessage();
        }
        return proto.InvitationAcceptedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    public Builder setInvitationAccepted(proto.InvitationAcceptedEvent value) {
      if (invitationAcceptedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        invitationAcceptedBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    public Builder setInvitationAccepted(
        proto.InvitationAcceptedEvent.Builder builderForValue) {
      if (invitationAcceptedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        invitationAcceptedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    public Builder mergeInvitationAccepted(proto.InvitationAcceptedEvent value) {
      if (invitationAcceptedBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != proto.InvitationAcceptedEvent.getDefaultInstance()) {
          event_ = proto.InvitationAcceptedEvent.newBuilder((proto.InvitationAcceptedEvent) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          invitationAcceptedBuilder_.mergeFrom(value);
        }
        invitationAcceptedBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    public Builder clearInvitationAccepted() {
      if (invitationAcceptedBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        invitationAcceptedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    public proto.InvitationAcceptedEvent.Builder getInvitationAcceptedBuilder() {
      return getInvitationAcceptedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    public proto.InvitationAcceptedEventOrBuilder getInvitationAcceptedOrBuilder() {
      if ((eventCase_ == 2) && (invitationAcceptedBuilder_ != null)) {
        return invitationAcceptedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (proto.InvitationAcceptedEvent) event_;
        }
        return proto.InvitationAcceptedEvent.getDefaultInstance();
      }
    }
    /**
     * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.InvitationAcceptedEvent, proto.InvitationAcceptedEvent.Builder, proto.InvitationAcceptedEventOrBuilder> 
        getInvitationAcceptedFieldBuilder() {
      if (invitationAcceptedBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = proto.InvitationAcceptedEvent.getDefaultInstance();
        }
        invitationAcceptedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.InvitationAcceptedEvent, proto.InvitationAcceptedEvent.Builder, proto.InvitationAcceptedEventOrBuilder>(
                (proto.InvitationAcceptedEvent) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();;
      return invitationAcceptedBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:WsEvent)
  }

  // @@protoc_insertion_point(class_scope:WsEvent)
  private static final proto.WsEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.WsEvent();
  }

  public static proto.WsEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WsEvent>
      PARSER = new com.google.protobuf.AbstractParser<WsEvent>() {
    public WsEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new WsEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WsEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WsEvent> getParserForType() {
    return PARSER;
  }

  public proto.WsEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

