// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws.proto

package proto;

public interface WsEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WsEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .InvitationEvent invitation = 1;</code>
   */
  proto.InvitationEvent getInvitation();
  /**
   * <code>optional .InvitationEvent invitation = 1;</code>
   */
  proto.InvitationEventOrBuilder getInvitationOrBuilder();

  /**
   * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
   */
  proto.InvitationAcceptedEvent getInvitationAccepted();
  /**
   * <code>optional .InvitationAcceptedEvent invitation_accepted = 2;</code>
   */
  proto.InvitationAcceptedEventOrBuilder getInvitationAcceptedOrBuilder();

  public proto.WsEvent.EventCase getEventCase();
}
